name: Manual Dev Deployment
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Enter branch to deploy"
        required: true
        default: "dev"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_OCR_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_OCR_BACKEND_URL }}
      # NEXT_PUBLIC_OCR_BACKEND_URL: "https://dev-ocr-backend-service-dot-ocr-dev-440305.el.r.appspot.com"
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - id: node-setup
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20"
      - id: install-dependencies
        name: Install node dependencies
        run: npm install
      - id: build-app
        name: Build App
        run: npm run build
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.OCR_DEPLOYMENT_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID }}
      - id: Deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: dev-app.yaml
